<a href="https://colab.research.google.com/github/omid-sakaki-ghazvini/Educations/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy:

In [ ]:
import numpy as np

<div style="direction:rtl">
<font color='red' size="5px">
 مثال:
    </font>
</div>

In [ ]:
a = np.array([1,2,3])

In [ ]:
b = np.array([[1],[2],[3]])

In [ ]:
c = np.array([[1,2,3]])

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([[1],
       [2],
       [3]])

In [ ]:
c

array([[1, 2, 3]])

In [ ]:
print(len(a), len(b), len(c))

3 3 1


In [ ]:
print(a.size, b.size, c.size)

3 3 3


In [ ]:
print(a.shape, b.shape, c.shape)

(3,) (3, 1) (1, 3)


In [ ]:
print(a.dtype, b.dtype, c.dtype)

int32 int32 int32


<div style="direction:rtl">
<font color='green' size="5px">
 بعضی توابع در
    numpy
    وجود دارد که با استفاده از آن می توانیم آرایه های با طول و عرض مشخص ایجاد نماییم
    </font>
</div>

In [ ]:
np.empty([3,2], dtype=int)

array([[-1603008848,         509],
       [          0,           0],
       [     131074,           0]])

<div style="direction:rtl">
<font color='green' size="5px">
 یک آرایه با 3 سطر و 2 ستون ایجاد میکند که با مقادیر تصادفی مقداردهی شده است.
    </font>
</div>

In [ ]:
np.zeros([6,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones([4,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.full([3,10], 0.3)

array([[0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3],
       [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3],
       [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]])

<div style="direction:rtl">
<font color='green' size="5px">
 میتوانیم لیست را تبدیل به آرایه numpy کنیم
    </font>
</div>

In [ ]:
x = [1,2,3]

In [ ]:
type(x)

list

In [ ]:
y = np.asarray(x)

In [ ]:
type(y)

numpy.ndarray

In [ ]:
for i in y:
    print(i)

1
2
3


<div style="direction:rtl">
<font color='green' size="5px">
 ایجاد آرایه در یک رنج مشخص
    </font>
</div>

In [ ]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<div style="direction:rtl">
<font color='green' size="5px">
 یک آرایه در رنج بین 10 تا 20 که با گام 2 حرکت کند
    </font>
</div>

In [ ]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

<div style="direction:rtl">
<font color='green' size="5px">
 یک آرایه در رنج بین 0 تا 15 که شامل 3 سطر و 5 ستون است، ایجاد کنید
    </font>
</div>

In [ ]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

<div style="direction:rtl">
<font color='green' size="5px">
 یک آرایه در رنج بین 0 تا 15 ایجاد کرده و سپس به 3 آرایه تقسیم میکنیم
    </font>
</div>

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.split(np.arange(15),3)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

<div style="direction:rtl">
<font color='green' size="5px">
 یک آرایه در رنج بین 10 تا 20 که با 5 اعداد تصادفی، ایجاد میکند
    </font>
</div>

In [ ]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

<div style="direction:rtl">
<font color='red' size="5px">
 مثال:
    </font>
</div>

In [ ]:
a = np.arange(10,40,5)
a

array([10, 15, 20, 25, 30, 35])

In [ ]:
b = list(map(lambda x: x*2, a))
b

[20, 30, 40, 50, 60, 70]

<div style="direction:rtl">
<font color='blue' size="5px">
تمرین 1 امتیازی: یک آرایه ایجاد کنید در رنج اعداد 10 تا 50 که شامل 10 عدد تصادفی است و از این آرایه اعدادی که کمتر از 25 هست را حذف کنید
    </font>
</div>

In [ ]:
a = np.linspace(10,50,10)
a

In [ ]:
b = list(filter(lambda x : x > 25, a))
b

<div style="direction:rtl">
<font color='green' size="5px">
 دسترسی به درایه های یک آرایه:
    </font>
</div>

In [ ]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2]

2

In [ ]:
a[2:5]

array([2, 3, 4])

In [ ]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b[1]

array([3, 4, 5])

In [ ]:
b[1,2]

5

In [ ]:
b[:,1]

array([1, 4, 7])

<div style="direction:rtl">
<font color='blue' size="5px">
تمرین 2 امتیازی: یک آرایه ایجاد کنید در رنج اعداد 10، سپس به 2 آرایه تقسیم نمایید و خروجی [(0, 5), (1, 6), (2, 7), (3, 8), (4, 9)] را تولید کنید
    </font>
</div>

# output: [(0, 5), (1, 6), (2, 7), (3, 8), (4, 9)]

In [ ]:
a = np.split(np.arange(10),2)
a

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
a[0]

array([0, 1, 2, 3, 4])

In [ ]:
b= list(zip(a[0],a[1]))
b

[(0, 5), (1, 6), (2, 7), (3, 8), (4, 9)]

<div style="direction:rtl">
<font color='red' size="5px">
 مثال:
    </font>
</div>

In [ ]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
b.resize((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<div style="direction:rtl">
<font color='red' size="5px">
 مثال:
    </font>
</div>

In [ ]:
a = np.array(([1,2,3],[4,5,6]))

print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
b = np.array(([7,8,9],[10,11,12]))

print(b)
b.shape

[[ 7  8  9]
 [10 11 12]]


(2, 3)

In [ ]:
x = np.concatenate((a,b), axis = 1)

print(x)
x.shape

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


(2, 6)

In [ ]:
x = np.resize(x, (6,2))

print(x)
x.shape

[[ 1  2]
 [ 3  7]
 [ 8  9]
 [ 4  5]
 [ 6 10]
 [11 12]]


(6, 2)

In [ ]:
y = np.concatenate((a,b), axis = 0)

print(y)
y.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [ ]:
y.diagonal()

array([1, 5, 9])

In [ ]:
a = np.array(([1,2,3],[4,5,6]))

print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
b = np.delete(a,1, axis=1)

print(b)
b.shape

[[1 3]
 [4 6]]


(2, 2)

In [ ]:
np.append(b,[[7,8]], axis=0)

array([[1, 3],
       [4, 6],
       [7, 8]])

In [ ]:
a = np.array(([1,2,3],[4,5,6]))

print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
b = np.delete(a,1, axis=0)

print(b)
b.shape

[[1 2 3]]


(1, 3)

In [ ]:
np.append(b,[[7,8,9]], axis=1)

array([[1, 2, 3, 7, 8, 9]])

In [ ]:
a = np.array(([1,2,3],[4,5,6]))
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.insert(a,1,[11], axis=1)

array([[ 1, 11,  2,  3],
       [ 4, 11,  5,  6]])

In [ ]:
np.insert(a,1,[11], axis=0)

array([[ 1,  2,  3],
       [11, 11, 11],
       [ 4,  5,  6]])

<div style="direction:rtl">
<font color='green' size="5px">
 عملگرها در آرایه ها:
    </font>
</div>

In [ ]:
a = np.array(([1,2,3],[4,5,6]))

b = np.array(([7,8,9],[10,11,12]))

print("a array:", a)
print("b array: ", b)

c = a+b

d = np.add(a,b)

print("a+b array: ", c)
print("np.add(a,b) array: ", d)

if c.all() == d.all():
    print("np.add(a,b) = a+b")

a array: [[1 2 3]
 [4 5 6]]
b array:  [[ 7  8  9]
 [10 11 12]]
a+b array:  [[ 8 10 12]
 [14 16 18]]
np.add(a,b) array:  [[ 8 10 12]
 [14 16 18]]
np.add(a,b) = a+b


In [ ]:
a = np.array(([1,2,3],[4,5,6]))
b = np.array(([7,8,9],[10,11,12]))

print("a array:", a)
print("b array: ", b)

c = a-b
d = np.subtract(a,b)

print("a-b array: ", c)
print("np.subtract(a,b) array: ", d)

if c.all() == d.all():
    print("np.subtract(a,b) = a-b")

a array: [[1 2 3]
 [4 5 6]]
b array:  [[ 7  8  9]
 [10 11 12]]
a-b array:  [[-6 -6 -6]
 [-6 -6 -6]]
np.subtract(a,b) array:  [[-6 -6 -6]
 [-6 -6 -6]]
np.subtract(a,b) = a-b


In [ ]:
a = np.array(([1,2,3],[4,5,6]))
b = np.array(([7,8,9],[10,11,12]))

print("a array:", a)
print("b array: ", b)

c = a*b
d = np.multiply(a,b)

print("a*b array: ", c)
print("np.multiply(a,b) array: ", d)

if c.all() == d.all():
    print("np.multiply(a,b) = a*b")

a array: [[1 2 3]
 [4 5 6]]
b array:  [[ 7  8  9]
 [10 11 12]]
a*b array:  [[ 7 16 27]
 [40 55 72]]
np.multiply(a,b) array:  [[ 7 16 27]
 [40 55 72]]
np.multiply(a,b) = a*b


In [ ]:
a = np.array(([1,2,3],[4,5,6]))
b = np.array(([7,8,9],[10,11,12]))

print("a array:", a)
print("b array: ", b)

c = a/b
d = np.divide(a,b)

print("a/b array: ", c)
print("np.divide(a,b) array: ", d)

if c.all() == d.all():
    print("np.divide(a,b) = a/b")

a array: [[1 2 3]
 [4 5 6]]
b array:  [[ 7  8  9]
 [10 11 12]]
a/b array:  [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
np.divide(a,b) array:  [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
np.divide(a,b) = a/b


<div style="direction:rtl">
<font color='blue' size="5px">
 تمرین:
    خروجی کد زیر چیست؟
    </font>
</div>

In [ ]:
a = np.arange(21,30)

b = a.reshape(3,3)

c = b.diagonal()

d = np.delete(c,1, axis=0)

e = b[1:-1]

f = e.flatten()

g = np.delete(f,2, axis=0)

h = g-d

print(h)

[ 3 -4]


<div style="direction:rtl">
<font color='red' size="5px">
 مثال:
    </font>
</div>

In [ ]:
a = np.array(([1,2,3],[4,5,6]))

print(np.sum(a,axis=0))

print(np.sum(a,axis=1))

[5 7 9]
[ 6 15]


<div style="direction:rtl">
<font color='blue' size="5px">
 تمرین:
    خروجی کد زیر چیست؟
    </font>
</div>

In [ ]:
a = np.array(([1,2,3],[4,5,6]))

b = np.split(a,2)

c = np.sum(a,axis=0)

d = b[0] + b[1]

if c.all() == d.all():
    print('yes')
else:
    print('no')

<div style="direction:rtl">
<font color='red' size="5px">
 مثال:
    </font>
</div>

In [ ]:
a = np.array(([1,2,3],[4,5,6]))
print('a array:', a, '\n')

print(a.shape,'\n')

b = np.expand_dims(a, axis = 0)
print('b array:', b, '\n')

print(b.shape,'\n')

c = np.squeeze(b, axis = 0)
print('c array:', c, '\n')

print(c.shape,'\n')

a array: [[1 2 3]
 [4 5 6]] 

(2, 3) 

b array: [[[1 2 3]
  [4 5 6]]] 

(1, 2, 3) 

c array: [[1 2 3]
 [4 5 6]] 

(2, 3) 



<div style="direction:rtl">
<font color='blue' size="5px">
 تمرین:
    خروجی کد زیر چیست؟
    </font>
</div>

In [ ]:
a = np.array(([1,2,3],[4,5,6]))

b = np.expand_dims(a, axis = 0)

c = a.reshape(3,2,1)

if c.shape == b.shape:
    print('yes')
else:
    print('no')

no


In [ ]:
a = np.array(([1,2,3],[4,5,6]))

b = np.expand_dims(a, axis = 0)

print(b.shape)

(1, 2, 3)


In [ ]:
a = np.array(([1,2,3],[4,5,6]))

b = np.expand_dims(a, axis = 0)

c = a.reshape(1,2,3)

if c.shape == b.shape:
    print('yes')
else:
    print('no')

yes


<div style="direction:rtl">
<font color='green' size="5px">
 کار کردن با رشته ها:
    </font>
</div>

In [ ]:
np.char.add(['hello '], ['omid'])

array(['hello omid'], dtype='<U10')

In [ ]:
np.char.multiply('hello ', 5)

array('hello hello hello hello hello ', dtype='<U30')

In [ ]:
np.char.center('hello', 50)

array('                      hello                       ', dtype='<U50')

In [ ]:
np.char.capitalize('hello omid')

array('Hello omid', dtype='<U10')

In [ ]:
np.char.title('hello omid')

array('Hello Omid', dtype='<U10')

In [ ]:
np.char.upper('hello omid')

array('HELLO OMID', dtype='<U10')

In [ ]:
np.char.lower('HELLO OMID')

array('hello omid', dtype='<U10')

In [ ]:
np.char.split('hello omid')

array(list(['hello', 'omid']), dtype=object)

In [ ]:
np.char.join('_', 'hello')

array('h_e_l_l_o', dtype='<U9')

In [ ]:
np.char.replace('hello omid', 'omid', 'amir')

array('hello amir', dtype='<U10')

<div style="direction:rtl">
<font color='green' size="5px">
 جبر خطی:
    </font>
</div>

<div style="direction:rtl">
<font color='red' size="5px">
 ضرب ماتریسی:
    </font>
</div>

In [ ]:
a = np.array(([1,2],[3,4]))
b = np.array(([5,6],[7,8]))

c = a*b

d = np.dot(a,b)

print("a*b array: ", c, '\n')

print("np.dot(a,b) array: ", d, '\n')

<div style="direction:rtl">
<font color='red' size="5px">
 ضرب داخلی:
    </font>
</div>

In [ ]:
a = np.array(([1,2],[3,4]))
b = np.array(([5,6],[7,8]))

c = a*b

d = np.inner(a,b)

print("a*b array: ", c, '\n')

print("np.inner(a,b) array: ", d, '\n')

a*b array: [ [ 1 * 5 , 2 * 6 ], [ 3 * 7 , 4 * 8 ] ]

np.dot(a,b) array: [ [ ( 1 * 5 ) + ( 2 * 7 ) , ( 1 * 6 ) + ( 2 * 8 ) ] , [ ( 3 * 5 ) + ( 4 * 7 ) , ( 3 * 6 ) + ( 4 * 8 ) ] ]

np.inner(a,b) array: [ [ ( 1 * 5 ) + ( 2 * 6 ) , ( 1 * 7 ) + ( 2 * 8 ) ] , [ ( 3 * 5 ) + ( 4 * 6 ) , ( 3 * 7 ) + ( 4 * 8 ) ] ]